export type ProductMaster = {
  id: string
  name: string
  code: string
  image: string
  quantity: string
  unit: string
  value: string
  couponGenerationFlag: 'Enabled' | 'Disabled'
  couponAllocationQuantity: string
  standardPacking: string
  moq: string
  basePrice: string
  status: string
}

export type BaseCategory = {
  id: string
  name: string
  slug: string
  code: string
  assortment: string
  description: string
  products: ProductMaster[]
}

export type PrimaryCategory = {
  id: string
  name: string
  slug: string
  segment: string
  description: string
  baseCategories: BaseCategory[]
}

export const PRODUCT_STATUS_OPTIONS = [
  { id: 'Active', name: 'Active' },
  { id: 'Inactive', name: 'Inactive' },
  { id: 'Discontinued', name: 'Discontinued' },
]

export const COUPON_FLAG_OPTIONS = [
  { id: 'Enabled', name: 'Enabled' },
  { id: 'Disabled', name: 'Disabled' },
]

const FILTER_PRODUCTS: ProductMaster[] = [
  {
    id: 'PRD-001',
    name: 'WaterFilter-XX01',
    code: 'WF-XX01',
    image: '/products/waterfilter-xx01.png',
    quantity: '50',
    unit: 'Units',
    value: '₹4,999',
    couponGenerationFlag: 'Enabled',
    couponAllocationQuantity: '500',
    standardPacking: 'Single Unit',
    moq: '25',
    basePrice: '₹4,500',
    status: 'Active',
  },
  {
    id: 'PRD-002',
    name: 'WaterFilter-XX05',
    code: 'WF-XX05',
    image: '/products/waterfilter-xx05.png',
    quantity: '80',
    unit: 'Units',
    value: '₹8,499',
    couponGenerationFlag: 'Enabled',
    couponAllocationQuantity: '800',
    standardPacking: 'Twin Pack',
    moq: '40',
    basePrice: '₹7,950',
    status: 'Active',
  },
  {
    id: 'PRD-003',
    name: 'WaterFilter-XL10',
    code: 'WF-XL10',
    image: '/products/waterfilter-xl10.png',
    quantity: '35',
    unit: 'Units',
    value: '₹9,899',
    couponGenerationFlag: 'Disabled',
    couponAllocationQuantity: '0',
    standardPacking: 'Single Unit',
    moq: '20',
    basePrice: '₹9,150',
    status: 'Inactive',
  },
  {
    id: 'PRD-033',
    name: 'WaterFilter-XX07',
    code: 'WF-XX07',
    image: '/products/waterfilter-xx07.png',
    quantity: '65',
    unit: 'Units',
    value: '₹6,299',
    couponGenerationFlag: 'Enabled',
    couponAllocationQuantity: '650',
    standardPacking: 'Single Unit',
    moq: '30',
    basePrice: '₹5,850',
    status: 'Active',
  },
  {
    id: 'PRD-034',
    name: 'WaterFilter-XX12',
    code: 'WF-XX12',
    image: '/products/waterfilter-xx12.png',
    quantity: '45',
    unit: 'Units',
    value: '₹7,599',
    couponGenerationFlag: 'Enabled',
    couponAllocationQuantity: '450',
    standardPacking: 'Single Unit',
    moq: '22',
    basePrice: '₹7,100',
    status: 'Active',
  },
  {
    id: 'PRD-035',
    name: 'WaterFilter-Premium',
    code: 'WF-PREM',
    image: '/products/waterfilter-premium.png',
    quantity: '30',
    unit: 'Units',
    value: '₹11,999',
    couponGenerationFlag: 'Disabled',
    couponAllocationQuantity: '0',
    standardPacking: 'Deluxe Pack',
    moq: '15',
    basePrice: '₹11,400',
    status: 'Active',
  },
]

const RO_PRODUCTS: ProductMaster[] = [
  {
    id: 'PRD-004',
    name: 'WaterFilter-ProMax',
    code: 'RO-PRO',
    image: '/products/ro-promax.png',
    quantity: '45',
    unit: 'Units',
    value: '₹12,499',
    couponGenerationFlag: 'Enabled',
    couponAllocationQuantity: '450',
    standardPacking: 'Single Unit',
    moq: '15',
    basePrice: '₹11,700',
    status: 'Active',
  },
  {
    id: 'PRD-005',
    name: 'WaterFilter-Lite',
    code: 'RO-LITE',
    image: '/products/ro-lite.png',
    quantity: '60',
    unit: 'Units',
    value: '₹9,999',
    couponGenerationFlag: 'Enabled',
    couponAllocationQuantity: '300',
    standardPacking: 'Single Unit',
    moq: '30',
    basePrice: '₹9,200',
    status: 'Inactive',
  },
  {
    id: 'PRD-006',
    name: 'WaterFilter-Edge',
    code: 'RO-EDGE',
    image: '/products/ro-edge.png',
    quantity: '25',
    unit: 'Units',
    value: '₹15,499',
    couponGenerationFlag: 'Disabled',
    couponAllocationQuantity: '0',
    standardPacking: 'Single Unit',
    moq: '10',
    basePrice: '₹14,850',
    status: 'Active',
  },
  {
    id: 'PRD-036',
    name: 'WaterFilter-UltraMax',
    code: 'RO-UMAX',
    image: '/products/ro-ultramax.png',
    quantity: '38',
    unit: 'Units',
    value: '₹13,999',
    couponGenerationFlag: 'Enabled',
    couponAllocationQuantity: '380',
    standardPacking: 'Single Unit',
    moq: '18',
    basePrice: '₹13,200',
    status: 'Active',
  },
  {
    id: 'PRD-037',
    name: 'WaterFilter-Compact',
    code: 'RO-COMP',
    image: '/products/ro-compact.png',
    quantity: '52',
    unit: 'Units',
    value: '₹10,799',
    couponGenerationFlag: 'Enabled',
    couponAllocationQuantity: '520',
    standardPacking: 'Single Unit',
    moq: '25',
    basePrice: '₹10,100',
    status: 'Active',
  },
]

const UV_PRODUCTS: ProductMaster[] = [
  {
    id: 'PRD-007',
    name: 'UVPure-Alpha',
    code: 'UV-ALPHA',
    image: '/products/uv-alpha.png',
    quantity: '70',
    unit: 'Units',
    value: '₹7,299',
    couponGenerationFlag: 'Enabled',
    couponAllocationQuantity: '700',
    standardPacking: 'Countertop',
    moq: '30',
    basePrice: '₹6,850',
    status: 'Active',
  },
  {
    id: 'PRD-008',
    name: 'UVPure-Beta',
    code: 'UV-BETA',
    image: '/products/uv-beta.png',
    quantity: '50',
    unit: 'Units',
    value: '₹8,199',
    couponGenerationFlag: 'Enabled',
    couponAllocationQuantity: '600',
    standardPacking: 'Wall Mount',
    moq: '25',
    basePrice: '₹7,750',
    status: 'Active',
  },
  {
    id: 'PRD-009',
    name: 'UVPure-Gamma',
    code: 'UV-GAMMA',
    image: '/products/uv-gamma.png',
    quantity: '40',
    unit: 'Units',
    value: '₹8,899',
    couponGenerationFlag: 'Disabled',
    couponAllocationQuantity: '0',
    standardPacking: 'Wall Mount',
    moq: '20',
    basePrice: '₹8,250',
    status: 'Active',
  },
  {
    id: 'PRD-038',
    name: 'UVPure-Delta',
    code: 'UV-DELTA',
    image: '/products/uv-delta.png',
    quantity: '58',
    unit: 'Units',
    value: '₹7,799',
    couponGenerationFlag: 'Enabled',
    couponAllocationQuantity: '580',
    standardPacking: 'Countertop',
    moq: '28',
    basePrice: '₹7,300',
    status: 'Active',
  },
  {
    id: 'PRD-039',
    name: 'UVPure-Omega',
    code: 'UV-OMEGA',
    image: '/products/uv-omega.png',
    quantity: '45',
    unit: 'Units',
    value: '₹9,499',
    couponGenerationFlag: 'Enabled',
    couponAllocationQuantity: '450',
    standardPacking: 'Wall Mount Premium',
    moq: '22',
    basePrice: '₹9,000',
    status: 'Active',
  },
]

const COPPER_PRODUCTS: ProductMaster[] = [
  {
    id: 'PRD-010',
    name: 'CopperPure-Max',
    code: 'CU-MAX',
    image: '/products/copper-max.png',
    quantity: '35',
    unit: 'Units',
    value: '₹10,499',
    couponGenerationFlag: 'Enabled',
    couponAllocationQuantity: '350',
    standardPacking: 'Single Unit',
    moq: '15',
    basePrice: '₹9,950',
    status: 'Active',
  },
  {
    id: 'PRD-011',
    name: 'CopperPure-Slim',
    code: 'CU-SLIM',
    image: '/products/copper-slim.png',
    quantity: '32',
    unit: 'Units',
    value: '₹9,299',
    couponGenerationFlag: 'Disabled',
    couponAllocationQuantity: '0',
    standardPacking: 'Single Unit',
    moq: '12',
    basePrice: '₹8,800',
    status: 'Discontinued',
  },
  {
    id: 'PRD-012',
    name: 'CopperPure-Eco',
    code: 'CU-ECO',
    image: '/products/copper-eco.png',
    quantity: '48',
    unit: 'Units',
    value: '₹9,899',
    couponGenerationFlag: 'Enabled',
    couponAllocationQuantity: '480',
    standardPacking: 'Single Unit',
    moq: '20',
    basePrice: '₹9,350',
    status: 'Active',
  },
  {
    id: 'PRD-040',
    name: 'CopperPure-Plus',
    code: 'CU-PLUS',
    image: '/products/copper-plus.png',
    quantity: '42',
    unit: 'Units',
    value: '₹10,999',
    couponGenerationFlag: 'Enabled',
    couponAllocationQuantity: '420',
    standardPacking: 'Single Unit',
    moq: '18',
    basePrice: '₹10,450',
    status: 'Active',
  },
]

const DISPENSER_FLOOR_PRODUCTS: ProductMaster[] = [
  {
    id: 'PRD-013',
    name: 'Dispense-Pro',
    code: 'DP-PRO',
    image: '/products/dispense-pro.png',
    quantity: '28',
    unit: 'Units',
    value: '₹14,999',
    couponGenerationFlag: 'Enabled',
    couponAllocationQuantity: '140',
    standardPacking: 'Single Unit',
    moq: '10',
    basePrice: '₹14,200',
    status: 'Active',
  },
  {
    id: 'PRD-014',
    name: 'Dispense-Go',
    code: 'DP-GO',
    image: '/products/dispense-go.png',
    quantity: '22',
    unit: 'Units',
    value: '₹12,999',
    couponGenerationFlag: 'Disabled',
    couponAllocationQuantity: '0',
    standardPacking: 'Single Unit',
    moq: '8',
    basePrice: '₹12,350',
    status: 'Inactive',
  },
  {
    id: 'PRD-015',
    name: 'Dispense-Elite',
    code: 'DP-ELITE',
    image: '/products/dispense-elite.png',
    quantity: '18',
    unit: 'Units',
    value: '₹16,499',
    couponGenerationFlag: 'Enabled',
    couponAllocationQuantity: '180',
    standardPacking: 'Single Unit',
    moq: '6',
    basePrice: '₹15,700',
    status: 'Active',
  },
  {
    id: 'PRD-041',
    name: 'Dispense-Smart',
    code: 'DP-SMART',
    image: '/products/dispense-smart.png',
    quantity: '25',
    unit: 'Units',
    value: '₹17,999',
    couponGenerationFlag: 'Enabled',
    couponAllocationQuantity: '250',
    standardPacking: 'Single Unit',
    moq: '8',
    basePrice: '₹17,200',
    status: 'Active',
  },
]

const DISPENSER_TABLE_PRODUCTS: ProductMaster[] = [
  {
    id: 'PRD-016',
    name: 'Dispense-Mini',
    code: 'DP-MINI',
    image: '/products/dispense-mini.png',
    quantity: '55',
    unit: 'Units',
    value: '₹11,499',
    couponGenerationFlag: 'Enabled',
    couponAllocationQuantity: '550',
    standardPacking: 'Single Unit',
    moq: '25',
    basePrice: '₹10,950',
    status: 'Active',
  },
  {
    id: 'PRD-017',
    name: 'Dispense-Cube',
    code: 'DP-CUBE',
    image: '/products/dispense-cube.png',
    quantity: '44',
    unit: 'Units',
    value: '₹10,799',
    couponGenerationFlag: 'Enabled',
    couponAllocationQuantity: '440',
    standardPacking: 'Single Unit',
    moq: '22',
    basePrice: '₹10,250',
    status: 'Active',
  },
  {
    id: 'PRD-018',
    name: 'Dispense-Pop',
    code: 'DP-POP',
    image: '/products/dispense-pop.png',
    quantity: '33',
    unit: 'Units',
    value: '₹9,799',
    couponGenerationFlag: 'Disabled',
    couponAllocationQuantity: '0',
    standardPacking: 'Single Unit',
    moq: '18',
    basePrice: '₹9,250',
    status: 'Active',
  },
  {
    id: 'PRD-042',
    name: 'Dispense-Nano',
    code: 'DP-NANO',
    image: '/products/dispense-nano.png',
    quantity: '62',
    unit: 'Units',
    value: '₹9,299',
    couponGenerationFlag: 'Enabled',
    couponAllocationQuantity: '620',
    standardPacking: 'Single Unit',
    moq: '30',
    basePrice: '₹8,800',
    status: 'Active',
  },
]

const SOFTENER_COMPACT_PRODUCTS: ProductMaster[] = [
  {
    id: 'PRD-019',
    name: 'SoftPure-City',
    code: 'SP-CITY',
    image: '/products/softpure-city.png',
    quantity: '26',
    unit: 'Units',
    value: '₹18,999',
    couponGenerationFlag: 'Enabled',
    couponAllocationQuantity: '260',
    standardPacking: 'Single Unit',
    moq: '8',
    basePrice: '₹18,200',
    status: 'Active',
  },
  {
    id: 'PRD-020',
    name: 'SoftPure-Metro',
    code: 'SP-METRO',
    image: '/products/softpure-metro.png',
    quantity: '20',
    unit: 'Units',
    value: '₹21,499',
    couponGenerationFlag: 'Enabled',
    couponAllocationQuantity: '200',
    standardPacking: 'Single Unit',
    moq: '6',
    basePrice: '₹20,750',
    status: 'Active',
  },
  {
    id: 'PRD-043',
    name: 'SoftPure-Home',
    code: 'SP-HOME',
    image: '/products/softpure-home.png',
    quantity: '32',
    unit: 'Units',
    value: '₹17,499',
    couponGenerationFlag: 'Enabled',
    couponAllocationQuantity: '320',
    standardPacking: 'Single Unit',
    moq: '10',
    basePrice: '₹16,750',
    status: 'Active',
  },
]

const SOFTENER_INDUSTRIAL_PRODUCTS: ProductMaster[] = [
  {
    id: 'PRD-021',
    name: 'SoftPro-Plant',
    code: 'SP-PLANT',
    image: '/products/softpro-plant.png',
    quantity: '12',
    unit: 'Units',
    value: '₹54,999',
    couponGenerationFlag: 'Disabled',
    couponAllocationQuantity: '0',
    standardPacking: 'Pallet',
    moq: '4',
    basePrice: '₹53,250',
    status: 'Active',
  },
  {
    id: 'PRD-022',
    name: 'SoftPro-Plant XL',
    code: 'SP-PLANT-XL',
    image: '/products/softpro-plant-xl.png',
    quantity: '10',
    unit: 'Units',
    value: '₹64,999',
    couponGenerationFlag: 'Disabled',
    couponAllocationQuantity: '0',
    standardPacking: 'Pallet',
    moq: '3',
    basePrice: '₹63,400',
    status: 'Active',
  },
  {
    id: 'PRD-044',
    name: 'SoftPro-Factory',
    code: 'SP-FACTORY',
    image: '/products/softpro-factory.png',
    quantity: '8',
    unit: 'Units',
    value: '₹74,999',
    couponGenerationFlag: 'Disabled',
    couponAllocationQuantity: '0',
    standardPacking: 'Pallet',
    moq: '2',
    basePrice: '₹73,500',
    status: 'Active',
  },
]

const ACCESSORY_FILTER_PRODUCTS: ProductMaster[] = [
  {
    id: 'PRD-023',
    name: 'Cartridge-Classic',
    code: 'AC-CLASSIC',
    image: '/products/cartridge-classic.png',
    quantity: '200',
    unit: 'Pieces',
    value: '₹999',
    couponGenerationFlag: 'Enabled',
    couponAllocationQuantity: '1000',
    standardPacking: 'Box of 10',
    moq: '100',
    basePrice: '₹920',
    status: 'Active',
  },
  {
    id: 'PRD-024',
    name: 'Cartridge-Advance',
    code: 'AC-ADV',
    image: '/products/cartridge-advance.png',
    quantity: '150',
    unit: 'Pieces',
    value: '₹1,499',
    couponGenerationFlag: 'Enabled',
    couponAllocationQuantity: '800',
    standardPacking: 'Box of 10',
    moq: '80',
    basePrice: '₹1,420',
    status: 'Active',
  },
  {
    id: 'PRD-045',
    name: 'Cartridge-Premium',
    code: 'AC-PREM',
    image: '/products/cartridge-premium.png',
    quantity: '120',
    unit: 'Pieces',
    value: '₹1,999',
    couponGenerationFlag: 'Enabled',
    couponAllocationQuantity: '600',
    standardPacking: 'Box of 10',
    moq: '60',
    basePrice: '₹1,850',
    status: 'Active',
  },
]

const ACCESSORY_INSTALL_PRODUCTS: ProductMaster[] = [
  {
    id: 'PRD-025',
    name: 'InstallKit-Standard',
    code: 'IK-STD',
    image: '/products/installkit-standard.png',
    quantity: '120',
    unit: 'Kits',
    value: '₹2,499',
    couponGenerationFlag: 'Enabled',
    couponAllocationQuantity: '400',
    standardPacking: 'Kit',
    moq: '60',
    basePrice: '₹2,250',
    status: 'Active',
  },
  {
    id: 'PRD-026',
    name: 'InstallKit-Pro',
    code: 'IK-PRO',
    image: '/products/installkit-pro.png',
    quantity: '90',
    unit: 'Kits',
    value: '₹3,199',
    couponGenerationFlag: 'Enabled',
    couponAllocationQuantity: '320',
    standardPacking: 'Kit',
    moq: '45',
    basePrice: '₹2,950',
    status: 'Active',
  },
  {
    id: 'PRD-046',
    name: 'InstallKit-DIY',
    code: 'IK-DIY',
    image: '/products/installkit-diy.png',
    quantity: '150',
    unit: 'Kits',
    value: '₹1,799',
    couponGenerationFlag: 'Enabled',
    couponAllocationQuantity: '600',
    standardPacking: 'Kit',
    moq: '75',
    basePrice: '₹1,650',
    status: 'Active',
  },
]

const ACCESSORY_SMART_PRODUCTS: ProductMaster[] = [
  {
    id: 'PRD-027',
    name: 'SmartMonitor-Lite',
    code: 'SM-LITE',
    image: '/products/smartmonitor-lite.png',
    quantity: '60',
    unit: 'Units',
    value: '₹4,499',
    couponGenerationFlag: 'Enabled',
    couponAllocationQuantity: '240',
    standardPacking: 'Single Unit',
    moq: '20',
    basePrice: '₹4,050',
    status: 'Active',
  },
  {
    id: 'PRD-028',
    name: 'SmartMonitor-Pro',
    code: 'SM-PRO',
    image: '/products/smartmonitor-pro.png',
    quantity: '48',
    unit: 'Units',
    value: '₹5,999',
    couponGenerationFlag: 'Enabled',
    couponAllocationQuantity: '190',
    standardPacking: 'Single Unit',
    moq: '16',
    basePrice: '₹5,550',
    status: 'Active',
  },
]

export const productHierarchy: PrimaryCategory[] = [
  {
    id: 'PC-001',
    name: 'Filter',
    slug: 'filter',
    segment: 'Main Category of Item',
    description: 'Core filtration systems for both consumer and trade channels.',
    baseCategories: [
      {
        id: 'BC-001',
        name: 'Water Filter',
        slug: 'water-filter',
        code: 'WF-01',
        assortment: 'Product Categorization',
        description: 'Gravity, countertop, and inline water filters.',
        products: FILTER_PRODUCTS,
      },
      {
        id: 'BC-002',
        name: 'RO Filter',
        slug: 'ro-filter',
        code: 'RO-02',
        assortment: 'Product Categorization',
        description: 'Reverse osmosis filters for premium SKUs.',
        products: RO_PRODUCTS,
      },
      {
        id: 'BC-003',
        name: 'Faucet Filter',
        slug: 'faucet-filter',
        code: 'FF-04',
        assortment: 'Product Categorization',
        description: 'Plug-and-play faucet filters for rapid deployments.',
        products: [
          {
            id: 'PRD-029',
            name: 'TapSafe-Swift',
            code: 'TS-SWIFT',
            image: '/products/tapsafe-swift.png',
            quantity: '95',
            unit: 'Units',
            value: '₹3,299',
            couponGenerationFlag: 'Enabled',
            couponAllocationQuantity: '950',
            standardPacking: 'Single Unit',
            moq: '45',
            basePrice: '₹2,950',
            status: 'Active',
          },
          {
            id: 'PRD-030',
            name: 'TapSafe-Pure',
            code: 'TS-PURE',
            image: '/products/tapsafe-pure.png',
            quantity: '80',
            unit: 'Units',
            value: '₹3,899',
            couponGenerationFlag: 'Disabled',
            couponAllocationQuantity: '0',
            standardPacking: 'Single Unit',
            moq: '35',
            basePrice: '₹3,550',
            status: 'Active',
          },
        ],
      },
    ],
  },
  {
    id: 'PC-002',
    name: 'Purifier',
    slug: 'purifier',
    segment: 'Product Categorization',
    description: 'Chemical and UV purification product family.',
    baseCategories: [
      {
        id: 'BC-004',
        name: 'UV Purifier',
        slug: 'uv-purifier',
        code: 'UV-10',
        assortment: 'Product Categorization',
        description: 'Point-of-use UV based purifiers.',
        products: UV_PRODUCTS,
      },
      {
        id: 'BC-005',
        name: 'Copper Purifier',
        slug: 'copper-purifier',
        code: 'CU-05',
        assortment: 'Product Categorization',
        description: 'Purifiers with copper infusion.',
        products: COPPER_PRODUCTS,
      },
      {
        id: 'BC-006',
        name: 'Mineral Guard',
        slug: 'mineral-guard',
        code: 'MG-07',
        assortment: 'Product Categorization',
        description: 'Purifiers that retain essential minerals for taste.',
        products: [
          {
            id: 'PRD-031',
            name: 'MinGuard-Prime',
            code: 'MG-PRIME',
            image: '/products/minguard-prime.png',
            quantity: '38',
            unit: 'Units',
            value: '₹11,299',
            couponGenerationFlag: 'Enabled',
            couponAllocationQuantity: '380',
            standardPacking: 'Single Unit',
            moq: '18',
            basePrice: '₹10,750',
            status: 'Active',
          },
          {
            id: 'PRD-032',
            name: 'MinGuard-Micro',
            code: 'MG-MICRO',
            image: '/products/minguard-micro.png',
            quantity: '42',
            unit: 'Units',
            value: '₹9,899',
            couponGenerationFlag: 'Enabled',
            couponAllocationQuantity: '420',
            standardPacking: 'Single Unit',
            moq: '20',
            basePrice: '₹9,350',
            status: 'Active',
          },
        ],
      },
    ],
  },
  {
    id: 'PC-003',
    name: 'Dispenser',
    slug: 'dispenser',
    segment: 'Product Categorization',
    description: 'Hot and cold water dispensers.',
    baseCategories: [
      {
        id: 'BC-007',
        name: 'Floor Standing',
        slug: 'floor-standing',
        code: 'FD-11',
        assortment: 'Product Categorization',
        description: 'Commercial floor standing dispensers.',
        products: DISPENSER_FLOOR_PRODUCTS,
      },
      {
        id: 'BC-008',
        name: 'Table Top',
        slug: 'table-top',
        code: 'TT-03',
        assortment: 'Product Categorization',
        description: 'Compact dispensers for small offices.',
        products: DISPENSER_TABLE_PRODUCTS,
      },
    ],
  },
  {
    id: 'PC-004',
    name: 'Softener',
    slug: 'softener',
    segment: 'Industrial Solutions',
    description: 'Residential and industrial water softening solutions.',
    baseCategories: [
      {
        id: 'BC-009',
        name: 'Compact Softener',
        slug: 'compact-softener',
        code: 'CS-09',
        assortment: 'Residential',
        description: 'Space-saving softeners for apartments and homes.',
        products: SOFTENER_COMPACT_PRODUCTS,
      },
      {
        id: 'BC-010',
        name: 'Industrial Softener',
        slug: 'industrial-softener',
        code: 'IS-12',
        assortment: 'Industrial',
        description: 'Large capacity softeners for plants and factories.',
        products: SOFTENER_INDUSTRIAL_PRODUCTS,
      },
    ],
  },
  {
    id: 'PC-005',
    name: 'Accessories',
    slug: 'accessories',
    segment: 'After Market',
    description: 'Consumables and smart accessories for filtration systems.',
    baseCategories: [
      {
        id: 'BC-011',
        name: 'Filter Cartridge',
        slug: 'filter-cartridge',
        code: 'FC-13',
        assortment: 'Consumables',
        description: 'Replacement cartridges across micron ratings.',
        products: ACCESSORY_FILTER_PRODUCTS,
      },
      {
        id: 'BC-012',
        name: 'Installation Kit',
        slug: 'installation-kit',
        code: 'IK-14',
        assortment: 'Install Support',
        description: 'DIY and professional install kits.',
        products: ACCESSORY_INSTALL_PRODUCTS,
      },
      {
        id: 'BC-013',
        name: 'Smart Monitor',
        slug: 'smart-monitor',
        code: 'SM-15',
        assortment: 'Connected Devices',
        description: 'IoT add-ons for monitoring filter health.',
        products: ACCESSORY_SMART_PRODUCTS,
      },
    ],
  },
]

export function slugifyLabel(value: string): string {
  return value
    .toLowerCase()
    .replace(/&/g, 'and')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)+/g, '')
}
